//autogenerated code - do not modify - see maskgen
//parameters: conductance_array_size 130, couplerange 15, couple_array_size 31
#include <stdio.h>
#include "sizes.h"
#include "mymath.h"
#include "paramheader.h"
long long int c  = 0;
void evolvept_duallayer (const int x,const int y,const Compute_float* const __restrict connections,const Compute_float strmod, Compute_float* __restrict condmat)
{
c++;    const int outoff0 = ((x+0)*130 + y);
    const int conoff0 = 0*couple_array_size;
    for (int kk=(couplerange-0);kk<=(couplerange+0);kk++)
    {
        condmat[outoff0 + kk] += connections[conoff0+kk]*strmod;
    }
    const int outoff1 = ((x+1)*130 + y);
    const int conoff1 = 1*couple_array_size;
    for (int kk=(couplerange-5);kk<=(couplerange+5);kk++)
    {
        condmat[outoff1 + kk] += connections[conoff1+kk]*strmod;
    }
    const int outoff2 = ((x+2)*130 + y);
    const int conoff2 = 2*couple_array_size;
    for (int kk=(couplerange-7);kk<=(couplerange+7);kk++)
    {
        condmat[outoff2 + kk] += connections[conoff2+kk]*strmod;
    }
    const int outoff3 = ((x+3)*130 + y);
    const int conoff3 = 3*couple_array_size;
    for (int kk=(couplerange-9);kk<=(couplerange+9);kk++)
    {
        condmat[outoff3 + kk] += connections[conoff3+kk]*strmod;
    }
    const int outoff4 = ((x+4)*130 + y);
    const int conoff4 = 4*couple_array_size;
    for (int kk=(couplerange-10);kk<=(couplerange+10);kk++)
    {
        condmat[outoff4 + kk] += connections[conoff4+kk]*strmod;
    }
    const int outoff5 = ((x+5)*130 + y);
    const int conoff5 = 5*couple_array_size;
    for (int kk=(couplerange-11);kk<=(couplerange+11);kk++)
    {
        condmat[outoff5 + kk] += connections[conoff5+kk]*strmod;
    }
    const int outoff6 = ((x+6)*130 + y);
    const int conoff6 = 6*couple_array_size;
    for (int kk=(couplerange-12);kk<=(couplerange+12);kk++)
    {
        condmat[outoff6 + kk] += connections[conoff6+kk]*strmod;
    }
    const int outoff7 = ((x+7)*130 + y);
    const int conoff7 = 7*couple_array_size;
    for (int kk=(couplerange-12);kk<=(couplerange+12);kk++)
    {
        condmat[outoff7 + kk] += connections[conoff7+kk]*strmod;
    }
    const int outoff8 = ((x+8)*130 + y);
    const int conoff8 = 8*couple_array_size;
    for (int kk=(couplerange-13);kk<=(couplerange+13);kk++)
    {
        condmat[outoff8 + kk] += connections[conoff8+kk]*strmod;
    }
    const int outoff9 = ((x+9)*130 + y);
    const int conoff9 = 9*couple_array_size;
    for (int kk=(couplerange-13);kk<=(couplerange+13);kk++)
    {
        condmat[outoff9 + kk] += connections[conoff9+kk]*strmod;
    }
    const int outoff10 = ((x+10)*130 + y);
    const int conoff10 = 10*couple_array_size;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        condmat[outoff10 + kk] += connections[conoff10+kk]*strmod;
    }
    const int outoff11 = ((x+11)*130 + y);
    const int conoff11 = 11*couple_array_size;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        condmat[outoff11 + kk] += connections[conoff11+kk]*strmod;
    }
    const int outoff12 = ((x+12)*130 + y);
    const int conoff12 = 12*couple_array_size;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        condmat[outoff12 + kk] += connections[conoff12+kk]*strmod;
    }
    const int outoff13 = ((x+13)*130 + y);
    const int conoff13 = 13*couple_array_size;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        condmat[outoff13 + kk] += connections[conoff13+kk]*strmod;
    }
    const int outoff14 = ((x+14)*130 + y);
    const int conoff14 = 14*couple_array_size;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        condmat[outoff14 + kk] += connections[conoff14+kk]*strmod;
    }
    const int outoff15 = ((x+15)*130 + y);
    const int conoff15 = 15*couple_array_size;
    for (int kk=(couplerange-15);kk<=(couplerange+15);kk++)
    {
        condmat[outoff15 + kk] += connections[conoff15+kk]*strmod;
    }
    const int outoff16 = ((x+16)*130 + y);
    const int conoff16 = 16*couple_array_size;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        condmat[outoff16 + kk] += connections[conoff16+kk]*strmod;
    }
    const int outoff17 = ((x+17)*130 + y);
    const int conoff17 = 17*couple_array_size;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        condmat[outoff17 + kk] += connections[conoff17+kk]*strmod;
    }
    const int outoff18 = ((x+18)*130 + y);
    const int conoff18 = 18*couple_array_size;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        condmat[outoff18 + kk] += connections[conoff18+kk]*strmod;
    }
    const int outoff19 = ((x+19)*130 + y);
    const int conoff19 = 19*couple_array_size;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        condmat[outoff19 + kk] += connections[conoff19+kk]*strmod;
    }
    const int outoff20 = ((x+20)*130 + y);
    const int conoff20 = 20*couple_array_size;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        condmat[outoff20 + kk] += connections[conoff20+kk]*strmod;
    }
    const int outoff21 = ((x+21)*130 + y);
    const int conoff21 = 21*couple_array_size;
    for (int kk=(couplerange-13);kk<=(couplerange+13);kk++)
    {
        condmat[outoff21 + kk] += connections[conoff21+kk]*strmod;
    }
    const int outoff22 = ((x+22)*130 + y);
    const int conoff22 = 22*couple_array_size;
    for (int kk=(couplerange-13);kk<=(couplerange+13);kk++)
    {
        condmat[outoff22 + kk] += connections[conoff22+kk]*strmod;
    }
    const int outoff23 = ((x+23)*130 + y);
    const int conoff23 = 23*couple_array_size;
    for (int kk=(couplerange-12);kk<=(couplerange+12);kk++)
    {
        condmat[outoff23 + kk] += connections[conoff23+kk]*strmod;
    }
    const int outoff24 = ((x+24)*130 + y);
    const int conoff24 = 24*couple_array_size;
    for (int kk=(couplerange-12);kk<=(couplerange+12);kk++)
    {
        condmat[outoff24 + kk] += connections[conoff24+kk]*strmod;
    }
    const int outoff25 = ((x+25)*130 + y);
    const int conoff25 = 25*couple_array_size;
    for (int kk=(couplerange-11);kk<=(couplerange+11);kk++)
    {
        condmat[outoff25 + kk] += connections[conoff25+kk]*strmod;
    }
    const int outoff26 = ((x+26)*130 + y);
    const int conoff26 = 26*couple_array_size;
    for (int kk=(couplerange-10);kk<=(couplerange+10);kk++)
    {
        condmat[outoff26 + kk] += connections[conoff26+kk]*strmod;
    }
    const int outoff27 = ((x+27)*130 + y);
    const int conoff27 = 27*couple_array_size;
    for (int kk=(couplerange-9);kk<=(couplerange+9);kk++)
    {
        condmat[outoff27 + kk] += connections[conoff27+kk]*strmod;
    }
    const int outoff28 = ((x+28)*130 + y);
    const int conoff28 = 28*couple_array_size;
    for (int kk=(couplerange-7);kk<=(couplerange+7);kk++)
    {
        condmat[outoff28 + kk] += connections[conoff28+kk]*strmod;
    }
    const int outoff29 = ((x+29)*130 + y);
    const int conoff29 = 29*couple_array_size;
    for (int kk=(couplerange-5);kk<=(couplerange+5);kk++)
    {
        condmat[outoff29 + kk] += connections[conoff29+kk]*strmod;
    }
    const int outoff30 = ((x+30)*130 + y);
    const int conoff30 = 30*couple_array_size;
    for (int kk=(couplerange-0);kk<=(couplerange+0);kk++)
    {
        condmat[outoff30 + kk] += connections[conoff30+kk]*strmod;
    }
}
void evolvept_duallayer_STDP (const int x,const int y,const Compute_float* const __restrict connections,const Compute_float* const __restrict STDP_connections,const Compute_float strmod, Compute_float* __restrict condmat)
{
    const int outoff0 = ((x+0)*130 + y);
    const int conoff0 = 0*couple_array_size;
    const int STDPoff0 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff0;
    for (int kk=(couplerange-0);kk<=(couplerange+0);kk++)
    {
        condmat[outoff0 + kk] += (connections[conoff0+kk] + STDP_connections[STDPoff0+kk])*strmod;
    }
    const int outoff1 = ((x+1)*130 + y);
    const int conoff1 = 1*couple_array_size;
    const int STDPoff1 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff1;
    for (int kk=(couplerange-5);kk<=(couplerange+5);kk++)
    {
        condmat[outoff1 + kk] += (connections[conoff1+kk] + STDP_connections[STDPoff1+kk])*strmod;
    }
    const int outoff2 = ((x+2)*130 + y);
    const int conoff2 = 2*couple_array_size;
    const int STDPoff2 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff2;
    for (int kk=(couplerange-7);kk<=(couplerange+7);kk++)
    {
        condmat[outoff2 + kk] += (connections[conoff2+kk] + STDP_connections[STDPoff2+kk])*strmod;
    }
    const int outoff3 = ((x+3)*130 + y);
    const int conoff3 = 3*couple_array_size;
    const int STDPoff3 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff3;
    for (int kk=(couplerange-9);kk<=(couplerange+9);kk++)
    {
        condmat[outoff3 + kk] += (connections[conoff3+kk] + STDP_connections[STDPoff3+kk])*strmod;
    }
    const int outoff4 = ((x+4)*130 + y);
    const int conoff4 = 4*couple_array_size;
    const int STDPoff4 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff4;
    for (int kk=(couplerange-10);kk<=(couplerange+10);kk++)
    {
        condmat[outoff4 + kk] += (connections[conoff4+kk] + STDP_connections[STDPoff4+kk])*strmod;
    }
    const int outoff5 = ((x+5)*130 + y);
    const int conoff5 = 5*couple_array_size;
    const int STDPoff5 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff5;
    for (int kk=(couplerange-11);kk<=(couplerange+11);kk++)
    {
        condmat[outoff5 + kk] += (connections[conoff5+kk] + STDP_connections[STDPoff5+kk])*strmod;
    }
    const int outoff6 = ((x+6)*130 + y);
    const int conoff6 = 6*couple_array_size;
    const int STDPoff6 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff6;
    for (int kk=(couplerange-12);kk<=(couplerange+12);kk++)
    {
        condmat[outoff6 + kk] += (connections[conoff6+kk] + STDP_connections[STDPoff6+kk])*strmod;
    }
    const int outoff7 = ((x+7)*130 + y);
    const int conoff7 = 7*couple_array_size;
    const int STDPoff7 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff7;
    for (int kk=(couplerange-12);kk<=(couplerange+12);kk++)
    {
        condmat[outoff7 + kk] += (connections[conoff7+kk] + STDP_connections[STDPoff7+kk])*strmod;
    }
    const int outoff8 = ((x+8)*130 + y);
    const int conoff8 = 8*couple_array_size;
    const int STDPoff8 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff8;
    for (int kk=(couplerange-13);kk<=(couplerange+13);kk++)
    {
        condmat[outoff8 + kk] += (connections[conoff8+kk] + STDP_connections[STDPoff8+kk])*strmod;
    }
    const int outoff9 = ((x+9)*130 + y);
    const int conoff9 = 9*couple_array_size;
    const int STDPoff9 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff9;
    for (int kk=(couplerange-13);kk<=(couplerange+13);kk++)
    {
        condmat[outoff9 + kk] += (connections[conoff9+kk] + STDP_connections[STDPoff9+kk])*strmod;
    }
    const int outoff10 = ((x+10)*130 + y);
    const int conoff10 = 10*couple_array_size;
    const int STDPoff10 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff10;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        condmat[outoff10 + kk] += (connections[conoff10+kk] + STDP_connections[STDPoff10+kk])*strmod;
    }
    const int outoff11 = ((x+11)*130 + y);
    const int conoff11 = 11*couple_array_size;
    const int STDPoff11 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff11;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        condmat[outoff11 + kk] += (connections[conoff11+kk] + STDP_connections[STDPoff11+kk])*strmod;
    }
    const int outoff12 = ((x+12)*130 + y);
    const int conoff12 = 12*couple_array_size;
    const int STDPoff12 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff12;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        condmat[outoff12 + kk] += (connections[conoff12+kk] + STDP_connections[STDPoff12+kk])*strmod;
    }
    const int outoff13 = ((x+13)*130 + y);
    const int conoff13 = 13*couple_array_size;
    const int STDPoff13 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff13;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        condmat[outoff13 + kk] += (connections[conoff13+kk] + STDP_connections[STDPoff13+kk])*strmod;
    }
    const int outoff14 = ((x+14)*130 + y);
    const int conoff14 = 14*couple_array_size;
    const int STDPoff14 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff14;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        condmat[outoff14 + kk] += (connections[conoff14+kk] + STDP_connections[STDPoff14+kk])*strmod;
    }
    const int outoff15 = ((x+15)*130 + y);
    const int conoff15 = 15*couple_array_size;
    const int STDPoff15 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff15;
    for (int kk=(couplerange-15);kk<=(couplerange+15);kk++)
    {
        condmat[outoff15 + kk] += (connections[conoff15+kk] + STDP_connections[STDPoff15+kk])*strmod;
    }
    const int outoff16 = ((x+16)*130 + y);
    const int conoff16 = 16*couple_array_size;
    const int STDPoff16 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff16;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        condmat[outoff16 + kk] += (connections[conoff16+kk] + STDP_connections[STDPoff16+kk])*strmod;
    }
    const int outoff17 = ((x+17)*130 + y);
    const int conoff17 = 17*couple_array_size;
    const int STDPoff17 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff17;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        condmat[outoff17 + kk] += (connections[conoff17+kk] + STDP_connections[STDPoff17+kk])*strmod;
    }
    const int outoff18 = ((x+18)*130 + y);
    const int conoff18 = 18*couple_array_size;
    const int STDPoff18 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff18;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        condmat[outoff18 + kk] += (connections[conoff18+kk] + STDP_connections[STDPoff18+kk])*strmod;
    }
    const int outoff19 = ((x+19)*130 + y);
    const int conoff19 = 19*couple_array_size;
    const int STDPoff19 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff19;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        condmat[outoff19 + kk] += (connections[conoff19+kk] + STDP_connections[STDPoff19+kk])*strmod;
    }
    const int outoff20 = ((x+20)*130 + y);
    const int conoff20 = 20*couple_array_size;
    const int STDPoff20 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff20;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        condmat[outoff20 + kk] += (connections[conoff20+kk] + STDP_connections[STDPoff20+kk])*strmod;
    }
    const int outoff21 = ((x+21)*130 + y);
    const int conoff21 = 21*couple_array_size;
    const int STDPoff21 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff21;
    for (int kk=(couplerange-13);kk<=(couplerange+13);kk++)
    {
        condmat[outoff21 + kk] += (connections[conoff21+kk] + STDP_connections[STDPoff21+kk])*strmod;
    }
    const int outoff22 = ((x+22)*130 + y);
    const int conoff22 = 22*couple_array_size;
    const int STDPoff22 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff22;
    for (int kk=(couplerange-13);kk<=(couplerange+13);kk++)
    {
        condmat[outoff22 + kk] += (connections[conoff22+kk] + STDP_connections[STDPoff22+kk])*strmod;
    }
    const int outoff23 = ((x+23)*130 + y);
    const int conoff23 = 23*couple_array_size;
    const int STDPoff23 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff23;
    for (int kk=(couplerange-12);kk<=(couplerange+12);kk++)
    {
        condmat[outoff23 + kk] += (connections[conoff23+kk] + STDP_connections[STDPoff23+kk])*strmod;
    }
    const int outoff24 = ((x+24)*130 + y);
    const int conoff24 = 24*couple_array_size;
    const int STDPoff24 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff24;
    for (int kk=(couplerange-12);kk<=(couplerange+12);kk++)
    {
        condmat[outoff24 + kk] += (connections[conoff24+kk] + STDP_connections[STDPoff24+kk])*strmod;
    }
    const int outoff25 = ((x+25)*130 + y);
    const int conoff25 = 25*couple_array_size;
    const int STDPoff25 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff25;
    for (int kk=(couplerange-11);kk<=(couplerange+11);kk++)
    {
        condmat[outoff25 + kk] += (connections[conoff25+kk] + STDP_connections[STDPoff25+kk])*strmod;
    }
    const int outoff26 = ((x+26)*130 + y);
    const int conoff26 = 26*couple_array_size;
    const int STDPoff26 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff26;
    for (int kk=(couplerange-10);kk<=(couplerange+10);kk++)
    {
        condmat[outoff26 + kk] += (connections[conoff26+kk] + STDP_connections[STDPoff26+kk])*strmod;
    }
    const int outoff27 = ((x+27)*130 + y);
    const int conoff27 = 27*couple_array_size;
    const int STDPoff27 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff27;
    for (int kk=(couplerange-9);kk<=(couplerange+9);kk++)
    {
        condmat[outoff27 + kk] += (connections[conoff27+kk] + STDP_connections[STDPoff27+kk])*strmod;
    }
    const int outoff28 = ((x+28)*130 + y);
    const int conoff28 = 28*couple_array_size;
    const int STDPoff28 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff28;
    for (int kk=(couplerange-7);kk<=(couplerange+7);kk++)
    {
        condmat[outoff28 + kk] += (connections[conoff28+kk] + STDP_connections[STDPoff28+kk])*strmod;
    }
    const int outoff29 = ((x+29)*130 + y);
    const int conoff29 = 29*couple_array_size;
    const int STDPoff29 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff29;
    for (int kk=(couplerange-5);kk<=(couplerange+5);kk++)
    {
        condmat[outoff29 + kk] += (connections[conoff29+kk] + STDP_connections[STDPoff29+kk])*strmod;
    }
    const int outoff30 = ((x+30)*130 + y);
    const int conoff30 = 30*couple_array_size;
    const int STDPoff30 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff30;
    for (int kk=(couplerange-0);kk<=(couplerange+0);kk++)
    {
        condmat[outoff30 + kk] += (connections[conoff30+kk] + STDP_connections[STDPoff30+kk])*strmod;
    }
}
void AddRD (const int x,const int y,const Compute_float* const __restrict connections, Compute_float* __restrict Rmat,Compute_float* __restrict Dmat, const Compute_float R,const Compute_float D)
{
c++;const Compute_float Rstr = 1/(D-R);// * exp(-1*Features.Timestep/R) ;
const Compute_float Dstr = 1/(D-R);// * exp(-1*Features.Timestep/D);
    const int outoff0 = ((x+0)*130 + y);
    const int conoff0 = 0*couple_array_size;
    for (int kk=(couplerange-0);kk<=(couplerange+0);kk++)
    {
        Rmat[outoff0 + kk] += connections[conoff0+kk]*Rstr;
        Dmat[outoff0 + kk] += connections[conoff0+kk]*Dstr;
    }
    const int outoff1 = ((x+1)*130 + y);
    const int conoff1 = 1*couple_array_size;
    for (int kk=(couplerange-5);kk<=(couplerange+5);kk++)
    {
        Rmat[outoff1 + kk] += connections[conoff1+kk]*Rstr;
        Dmat[outoff1 + kk] += connections[conoff1+kk]*Dstr;
    }
    const int outoff2 = ((x+2)*130 + y);
    const int conoff2 = 2*couple_array_size;
    for (int kk=(couplerange-7);kk<=(couplerange+7);kk++)
    {
        Rmat[outoff2 + kk] += connections[conoff2+kk]*Rstr;
        Dmat[outoff2 + kk] += connections[conoff2+kk]*Dstr;
    }
    const int outoff3 = ((x+3)*130 + y);
    const int conoff3 = 3*couple_array_size;
    for (int kk=(couplerange-9);kk<=(couplerange+9);kk++)
    {
        Rmat[outoff3 + kk] += connections[conoff3+kk]*Rstr;
        Dmat[outoff3 + kk] += connections[conoff3+kk]*Dstr;
    }
    const int outoff4 = ((x+4)*130 + y);
    const int conoff4 = 4*couple_array_size;
    for (int kk=(couplerange-10);kk<=(couplerange+10);kk++)
    {
        Rmat[outoff4 + kk] += connections[conoff4+kk]*Rstr;
        Dmat[outoff4 + kk] += connections[conoff4+kk]*Dstr;
    }
    const int outoff5 = ((x+5)*130 + y);
    const int conoff5 = 5*couple_array_size;
    for (int kk=(couplerange-11);kk<=(couplerange+11);kk++)
    {
        Rmat[outoff5 + kk] += connections[conoff5+kk]*Rstr;
        Dmat[outoff5 + kk] += connections[conoff5+kk]*Dstr;
    }
    const int outoff6 = ((x+6)*130 + y);
    const int conoff6 = 6*couple_array_size;
    for (int kk=(couplerange-12);kk<=(couplerange+12);kk++)
    {
        Rmat[outoff6 + kk] += connections[conoff6+kk]*Rstr;
        Dmat[outoff6 + kk] += connections[conoff6+kk]*Dstr;
    }
    const int outoff7 = ((x+7)*130 + y);
    const int conoff7 = 7*couple_array_size;
    for (int kk=(couplerange-12);kk<=(couplerange+12);kk++)
    {
        Rmat[outoff7 + kk] += connections[conoff7+kk]*Rstr;
        Dmat[outoff7 + kk] += connections[conoff7+kk]*Dstr;
    }
    const int outoff8 = ((x+8)*130 + y);
    const int conoff8 = 8*couple_array_size;
    for (int kk=(couplerange-13);kk<=(couplerange+13);kk++)
    {
        Rmat[outoff8 + kk] += connections[conoff8+kk]*Rstr;
        Dmat[outoff8 + kk] += connections[conoff8+kk]*Dstr;
    }
    const int outoff9 = ((x+9)*130 + y);
    const int conoff9 = 9*couple_array_size;
    for (int kk=(couplerange-13);kk<=(couplerange+13);kk++)
    {
        Rmat[outoff9 + kk] += connections[conoff9+kk]*Rstr;
        Dmat[outoff9 + kk] += connections[conoff9+kk]*Dstr;
    }
    const int outoff10 = ((x+10)*130 + y);
    const int conoff10 = 10*couple_array_size;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        Rmat[outoff10 + kk] += connections[conoff10+kk]*Rstr;
        Dmat[outoff10 + kk] += connections[conoff10+kk]*Dstr;
    }
    const int outoff11 = ((x+11)*130 + y);
    const int conoff11 = 11*couple_array_size;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        Rmat[outoff11 + kk] += connections[conoff11+kk]*Rstr;
        Dmat[outoff11 + kk] += connections[conoff11+kk]*Dstr;
    }
    const int outoff12 = ((x+12)*130 + y);
    const int conoff12 = 12*couple_array_size;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        Rmat[outoff12 + kk] += connections[conoff12+kk]*Rstr;
        Dmat[outoff12 + kk] += connections[conoff12+kk]*Dstr;
    }
    const int outoff13 = ((x+13)*130 + y);
    const int conoff13 = 13*couple_array_size;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        Rmat[outoff13 + kk] += connections[conoff13+kk]*Rstr;
        Dmat[outoff13 + kk] += connections[conoff13+kk]*Dstr;
    }
    const int outoff14 = ((x+14)*130 + y);
    const int conoff14 = 14*couple_array_size;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        Rmat[outoff14 + kk] += connections[conoff14+kk]*Rstr;
        Dmat[outoff14 + kk] += connections[conoff14+kk]*Dstr;
    }
    const int outoff15 = ((x+15)*130 + y);
    const int conoff15 = 15*couple_array_size;
    for (int kk=(couplerange-15);kk<=(couplerange+15);kk++)
    {
        Rmat[outoff15 + kk] += connections[conoff15+kk]*Rstr;
        Dmat[outoff15 + kk] += connections[conoff15+kk]*Dstr;
    }
    const int outoff16 = ((x+16)*130 + y);
    const int conoff16 = 16*couple_array_size;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        Rmat[outoff16 + kk] += connections[conoff16+kk]*Rstr;
        Dmat[outoff16 + kk] += connections[conoff16+kk]*Dstr;
    }
    const int outoff17 = ((x+17)*130 + y);
    const int conoff17 = 17*couple_array_size;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        Rmat[outoff17 + kk] += connections[conoff17+kk]*Rstr;
        Dmat[outoff17 + kk] += connections[conoff17+kk]*Dstr;
    }
    const int outoff18 = ((x+18)*130 + y);
    const int conoff18 = 18*couple_array_size;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        Rmat[outoff18 + kk] += connections[conoff18+kk]*Rstr;
        Dmat[outoff18 + kk] += connections[conoff18+kk]*Dstr;
    }
    const int outoff19 = ((x+19)*130 + y);
    const int conoff19 = 19*couple_array_size;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        Rmat[outoff19 + kk] += connections[conoff19+kk]*Rstr;
        Dmat[outoff19 + kk] += connections[conoff19+kk]*Dstr;
    }
    const int outoff20 = ((x+20)*130 + y);
    const int conoff20 = 20*couple_array_size;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        Rmat[outoff20 + kk] += connections[conoff20+kk]*Rstr;
        Dmat[outoff20 + kk] += connections[conoff20+kk]*Dstr;
    }
    const int outoff21 = ((x+21)*130 + y);
    const int conoff21 = 21*couple_array_size;
    for (int kk=(couplerange-13);kk<=(couplerange+13);kk++)
    {
        Rmat[outoff21 + kk] += connections[conoff21+kk]*Rstr;
        Dmat[outoff21 + kk] += connections[conoff21+kk]*Dstr;
    }
    const int outoff22 = ((x+22)*130 + y);
    const int conoff22 = 22*couple_array_size;
    for (int kk=(couplerange-13);kk<=(couplerange+13);kk++)
    {
        Rmat[outoff22 + kk] += connections[conoff22+kk]*Rstr;
        Dmat[outoff22 + kk] += connections[conoff22+kk]*Dstr;
    }
    const int outoff23 = ((x+23)*130 + y);
    const int conoff23 = 23*couple_array_size;
    for (int kk=(couplerange-12);kk<=(couplerange+12);kk++)
    {
        Rmat[outoff23 + kk] += connections[conoff23+kk]*Rstr;
        Dmat[outoff23 + kk] += connections[conoff23+kk]*Dstr;
    }
    const int outoff24 = ((x+24)*130 + y);
    const int conoff24 = 24*couple_array_size;
    for (int kk=(couplerange-12);kk<=(couplerange+12);kk++)
    {
        Rmat[outoff24 + kk] += connections[conoff24+kk]*Rstr;
        Dmat[outoff24 + kk] += connections[conoff24+kk]*Dstr;
    }
    const int outoff25 = ((x+25)*130 + y);
    const int conoff25 = 25*couple_array_size;
    for (int kk=(couplerange-11);kk<=(couplerange+11);kk++)
    {
        Rmat[outoff25 + kk] += connections[conoff25+kk]*Rstr;
        Dmat[outoff25 + kk] += connections[conoff25+kk]*Dstr;
    }
    const int outoff26 = ((x+26)*130 + y);
    const int conoff26 = 26*couple_array_size;
    for (int kk=(couplerange-10);kk<=(couplerange+10);kk++)
    {
        Rmat[outoff26 + kk] += connections[conoff26+kk]*Rstr;
        Dmat[outoff26 + kk] += connections[conoff26+kk]*Dstr;
    }
    const int outoff27 = ((x+27)*130 + y);
    const int conoff27 = 27*couple_array_size;
    for (int kk=(couplerange-9);kk<=(couplerange+9);kk++)
    {
        Rmat[outoff27 + kk] += connections[conoff27+kk]*Rstr;
        Dmat[outoff27 + kk] += connections[conoff27+kk]*Dstr;
    }
    const int outoff28 = ((x+28)*130 + y);
    const int conoff28 = 28*couple_array_size;
    for (int kk=(couplerange-7);kk<=(couplerange+7);kk++)
    {
        Rmat[outoff28 + kk] += connections[conoff28+kk]*Rstr;
        Dmat[outoff28 + kk] += connections[conoff28+kk]*Dstr;
    }
    const int outoff29 = ((x+29)*130 + y);
    const int conoff29 = 29*couple_array_size;
    for (int kk=(couplerange-5);kk<=(couplerange+5);kk++)
    {
        Rmat[outoff29 + kk] += connections[conoff29+kk]*Rstr;
        Dmat[outoff29 + kk] += connections[conoff29+kk]*Dstr;
    }
    const int outoff30 = ((x+30)*130 + y);
    const int conoff30 = 30*couple_array_size;
    for (int kk=(couplerange-0);kk<=(couplerange+0);kk++)
    {
        Rmat[outoff30 + kk] += connections[conoff30+kk]*Rstr;
        Dmat[outoff30 + kk] += connections[conoff30+kk]*Dstr;
    }
}
void AddRD_STDP (const int x,const int y,const Compute_float* const __restrict connections,const Compute_float* const __restrict STDP_connections,Compute_float* __restrict Rmat, Compute_float* __restrict Dmat,const Compute_float R, const Compute_float D )
{
const Compute_float Rstr = 1/(D-R);// * exp(-1*Features.Timestep/R) ;
const Compute_float Dstr = 1/(D-R);// * exp(-1*Features.Timestep/D);
    const int outoff0 = ((x+0)*130 + y);
    const int conoff0 = 0*couple_array_size;
    const int STDPoff0 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff0;
    for (int kk=(couplerange-0);kk<=(couplerange+0);kk++)
    {
        Rmat[outoff0 + kk] += (connections[conoff0+kk] + STDP_connections[STDPoff0+kk])*Rstr;
        Dmat[outoff0 + kk] += (connections[conoff0+kk] + STDP_connections[STDPoff0+kk])*Dstr;
    }
    const int outoff1 = ((x+1)*130 + y);
    const int conoff1 = 1*couple_array_size;
    const int STDPoff1 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff1;
    for (int kk=(couplerange-5);kk<=(couplerange+5);kk++)
    {
        Rmat[outoff1 + kk] += (connections[conoff1+kk] + STDP_connections[STDPoff1+kk])*Rstr;
        Dmat[outoff1 + kk] += (connections[conoff1+kk] + STDP_connections[STDPoff1+kk])*Dstr;
    }
    const int outoff2 = ((x+2)*130 + y);
    const int conoff2 = 2*couple_array_size;
    const int STDPoff2 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff2;
    for (int kk=(couplerange-7);kk<=(couplerange+7);kk++)
    {
        Rmat[outoff2 + kk] += (connections[conoff2+kk] + STDP_connections[STDPoff2+kk])*Rstr;
        Dmat[outoff2 + kk] += (connections[conoff2+kk] + STDP_connections[STDPoff2+kk])*Dstr;
    }
    const int outoff3 = ((x+3)*130 + y);
    const int conoff3 = 3*couple_array_size;
    const int STDPoff3 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff3;
    for (int kk=(couplerange-9);kk<=(couplerange+9);kk++)
    {
        Rmat[outoff3 + kk] += (connections[conoff3+kk] + STDP_connections[STDPoff3+kk])*Rstr;
        Dmat[outoff3 + kk] += (connections[conoff3+kk] + STDP_connections[STDPoff3+kk])*Dstr;
    }
    const int outoff4 = ((x+4)*130 + y);
    const int conoff4 = 4*couple_array_size;
    const int STDPoff4 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff4;
    for (int kk=(couplerange-10);kk<=(couplerange+10);kk++)
    {
        Rmat[outoff4 + kk] += (connections[conoff4+kk] + STDP_connections[STDPoff4+kk])*Rstr;
        Dmat[outoff4 + kk] += (connections[conoff4+kk] + STDP_connections[STDPoff4+kk])*Dstr;
    }
    const int outoff5 = ((x+5)*130 + y);
    const int conoff5 = 5*couple_array_size;
    const int STDPoff5 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff5;
    for (int kk=(couplerange-11);kk<=(couplerange+11);kk++)
    {
        Rmat[outoff5 + kk] += (connections[conoff5+kk] + STDP_connections[STDPoff5+kk])*Rstr;
        Dmat[outoff5 + kk] += (connections[conoff5+kk] + STDP_connections[STDPoff5+kk])*Dstr;
    }
    const int outoff6 = ((x+6)*130 + y);
    const int conoff6 = 6*couple_array_size;
    const int STDPoff6 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff6;
    for (int kk=(couplerange-12);kk<=(couplerange+12);kk++)
    {
        Rmat[outoff6 + kk] += (connections[conoff6+kk] + STDP_connections[STDPoff6+kk])*Rstr;
        Dmat[outoff6 + kk] += (connections[conoff6+kk] + STDP_connections[STDPoff6+kk])*Dstr;
    }
    const int outoff7 = ((x+7)*130 + y);
    const int conoff7 = 7*couple_array_size;
    const int STDPoff7 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff7;
    for (int kk=(couplerange-12);kk<=(couplerange+12);kk++)
    {
        Rmat[outoff7 + kk] += (connections[conoff7+kk] + STDP_connections[STDPoff7+kk])*Rstr;
        Dmat[outoff7 + kk] += (connections[conoff7+kk] + STDP_connections[STDPoff7+kk])*Dstr;
    }
    const int outoff8 = ((x+8)*130 + y);
    const int conoff8 = 8*couple_array_size;
    const int STDPoff8 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff8;
    for (int kk=(couplerange-13);kk<=(couplerange+13);kk++)
    {
        Rmat[outoff8 + kk] += (connections[conoff8+kk] + STDP_connections[STDPoff8+kk])*Rstr;
        Dmat[outoff8 + kk] += (connections[conoff8+kk] + STDP_connections[STDPoff8+kk])*Dstr;
    }
    const int outoff9 = ((x+9)*130 + y);
    const int conoff9 = 9*couple_array_size;
    const int STDPoff9 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff9;
    for (int kk=(couplerange-13);kk<=(couplerange+13);kk++)
    {
        Rmat[outoff9 + kk] += (connections[conoff9+kk] + STDP_connections[STDPoff9+kk])*Rstr;
        Dmat[outoff9 + kk] += (connections[conoff9+kk] + STDP_connections[STDPoff9+kk])*Dstr;
    }
    const int outoff10 = ((x+10)*130 + y);
    const int conoff10 = 10*couple_array_size;
    const int STDPoff10 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff10;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        Rmat[outoff10 + kk] += (connections[conoff10+kk] + STDP_connections[STDPoff10+kk])*Rstr;
        Dmat[outoff10 + kk] += (connections[conoff10+kk] + STDP_connections[STDPoff10+kk])*Dstr;
    }
    const int outoff11 = ((x+11)*130 + y);
    const int conoff11 = 11*couple_array_size;
    const int STDPoff11 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff11;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        Rmat[outoff11 + kk] += (connections[conoff11+kk] + STDP_connections[STDPoff11+kk])*Rstr;
        Dmat[outoff11 + kk] += (connections[conoff11+kk] + STDP_connections[STDPoff11+kk])*Dstr;
    }
    const int outoff12 = ((x+12)*130 + y);
    const int conoff12 = 12*couple_array_size;
    const int STDPoff12 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff12;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        Rmat[outoff12 + kk] += (connections[conoff12+kk] + STDP_connections[STDPoff12+kk])*Rstr;
        Dmat[outoff12 + kk] += (connections[conoff12+kk] + STDP_connections[STDPoff12+kk])*Dstr;
    }
    const int outoff13 = ((x+13)*130 + y);
    const int conoff13 = 13*couple_array_size;
    const int STDPoff13 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff13;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        Rmat[outoff13 + kk] += (connections[conoff13+kk] + STDP_connections[STDPoff13+kk])*Rstr;
        Dmat[outoff13 + kk] += (connections[conoff13+kk] + STDP_connections[STDPoff13+kk])*Dstr;
    }
    const int outoff14 = ((x+14)*130 + y);
    const int conoff14 = 14*couple_array_size;
    const int STDPoff14 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff14;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        Rmat[outoff14 + kk] += (connections[conoff14+kk] + STDP_connections[STDPoff14+kk])*Rstr;
        Dmat[outoff14 + kk] += (connections[conoff14+kk] + STDP_connections[STDPoff14+kk])*Dstr;
    }
    const int outoff15 = ((x+15)*130 + y);
    const int conoff15 = 15*couple_array_size;
    const int STDPoff15 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff15;
    for (int kk=(couplerange-15);kk<=(couplerange+15);kk++)
    {
        Rmat[outoff15 + kk] += (connections[conoff15+kk] + STDP_connections[STDPoff15+kk])*Rstr;
        Dmat[outoff15 + kk] += (connections[conoff15+kk] + STDP_connections[STDPoff15+kk])*Dstr;
    }
    const int outoff16 = ((x+16)*130 + y);
    const int conoff16 = 16*couple_array_size;
    const int STDPoff16 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff16;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        Rmat[outoff16 + kk] += (connections[conoff16+kk] + STDP_connections[STDPoff16+kk])*Rstr;
        Dmat[outoff16 + kk] += (connections[conoff16+kk] + STDP_connections[STDPoff16+kk])*Dstr;
    }
    const int outoff17 = ((x+17)*130 + y);
    const int conoff17 = 17*couple_array_size;
    const int STDPoff17 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff17;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        Rmat[outoff17 + kk] += (connections[conoff17+kk] + STDP_connections[STDPoff17+kk])*Rstr;
        Dmat[outoff17 + kk] += (connections[conoff17+kk] + STDP_connections[STDPoff17+kk])*Dstr;
    }
    const int outoff18 = ((x+18)*130 + y);
    const int conoff18 = 18*couple_array_size;
    const int STDPoff18 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff18;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        Rmat[outoff18 + kk] += (connections[conoff18+kk] + STDP_connections[STDPoff18+kk])*Rstr;
        Dmat[outoff18 + kk] += (connections[conoff18+kk] + STDP_connections[STDPoff18+kk])*Dstr;
    }
    const int outoff19 = ((x+19)*130 + y);
    const int conoff19 = 19*couple_array_size;
    const int STDPoff19 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff19;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        Rmat[outoff19 + kk] += (connections[conoff19+kk] + STDP_connections[STDPoff19+kk])*Rstr;
        Dmat[outoff19 + kk] += (connections[conoff19+kk] + STDP_connections[STDPoff19+kk])*Dstr;
    }
    const int outoff20 = ((x+20)*130 + y);
    const int conoff20 = 20*couple_array_size;
    const int STDPoff20 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff20;
    for (int kk=(couplerange-14);kk<=(couplerange+14);kk++)
    {
        Rmat[outoff20 + kk] += (connections[conoff20+kk] + STDP_connections[STDPoff20+kk])*Rstr;
        Dmat[outoff20 + kk] += (connections[conoff20+kk] + STDP_connections[STDPoff20+kk])*Dstr;
    }
    const int outoff21 = ((x+21)*130 + y);
    const int conoff21 = 21*couple_array_size;
    const int STDPoff21 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff21;
    for (int kk=(couplerange-13);kk<=(couplerange+13);kk++)
    {
        Rmat[outoff21 + kk] += (connections[conoff21+kk] + STDP_connections[STDPoff21+kk])*Rstr;
        Dmat[outoff21 + kk] += (connections[conoff21+kk] + STDP_connections[STDPoff21+kk])*Dstr;
    }
    const int outoff22 = ((x+22)*130 + y);
    const int conoff22 = 22*couple_array_size;
    const int STDPoff22 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff22;
    for (int kk=(couplerange-13);kk<=(couplerange+13);kk++)
    {
        Rmat[outoff22 + kk] += (connections[conoff22+kk] + STDP_connections[STDPoff22+kk])*Rstr;
        Dmat[outoff22 + kk] += (connections[conoff22+kk] + STDP_connections[STDPoff22+kk])*Dstr;
    }
    const int outoff23 = ((x+23)*130 + y);
    const int conoff23 = 23*couple_array_size;
    const int STDPoff23 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff23;
    for (int kk=(couplerange-12);kk<=(couplerange+12);kk++)
    {
        Rmat[outoff23 + kk] += (connections[conoff23+kk] + STDP_connections[STDPoff23+kk])*Rstr;
        Dmat[outoff23 + kk] += (connections[conoff23+kk] + STDP_connections[STDPoff23+kk])*Dstr;
    }
    const int outoff24 = ((x+24)*130 + y);
    const int conoff24 = 24*couple_array_size;
    const int STDPoff24 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff24;
    for (int kk=(couplerange-12);kk<=(couplerange+12);kk++)
    {
        Rmat[outoff24 + kk] += (connections[conoff24+kk] + STDP_connections[STDPoff24+kk])*Rstr;
        Dmat[outoff24 + kk] += (connections[conoff24+kk] + STDP_connections[STDPoff24+kk])*Dstr;
    }
    const int outoff25 = ((x+25)*130 + y);
    const int conoff25 = 25*couple_array_size;
    const int STDPoff25 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff25;
    for (int kk=(couplerange-11);kk<=(couplerange+11);kk++)
    {
        Rmat[outoff25 + kk] += (connections[conoff25+kk] + STDP_connections[STDPoff25+kk])*Rstr;
        Dmat[outoff25 + kk] += (connections[conoff25+kk] + STDP_connections[STDPoff25+kk])*Dstr;
    }
    const int outoff26 = ((x+26)*130 + y);
    const int conoff26 = 26*couple_array_size;
    const int STDPoff26 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff26;
    for (int kk=(couplerange-10);kk<=(couplerange+10);kk++)
    {
        Rmat[outoff26 + kk] += (connections[conoff26+kk] + STDP_connections[STDPoff26+kk])*Rstr;
        Dmat[outoff26 + kk] += (connections[conoff26+kk] + STDP_connections[STDPoff26+kk])*Dstr;
    }
    const int outoff27 = ((x+27)*130 + y);
    const int conoff27 = 27*couple_array_size;
    const int STDPoff27 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff27;
    for (int kk=(couplerange-9);kk<=(couplerange+9);kk++)
    {
        Rmat[outoff27 + kk] += (connections[conoff27+kk] + STDP_connections[STDPoff27+kk])*Rstr;
        Dmat[outoff27 + kk] += (connections[conoff27+kk] + STDP_connections[STDPoff27+kk])*Dstr;
    }
    const int outoff28 = ((x+28)*130 + y);
    const int conoff28 = 28*couple_array_size;
    const int STDPoff28 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff28;
    for (int kk=(couplerange-7);kk<=(couplerange+7);kk++)
    {
        Rmat[outoff28 + kk] += (connections[conoff28+kk] + STDP_connections[STDPoff28+kk])*Rstr;
        Dmat[outoff28 + kk] += (connections[conoff28+kk] + STDP_connections[STDPoff28+kk])*Dstr;
    }
    const int outoff29 = ((x+29)*130 + y);
    const int conoff29 = 29*couple_array_size;
    const int STDPoff29 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff29;
    for (int kk=(couplerange-5);kk<=(couplerange+5);kk++)
    {
        Rmat[outoff29 + kk] += (connections[conoff29+kk] + STDP_connections[STDPoff29+kk])*Rstr;
        Dmat[outoff29 + kk] += (connections[conoff29+kk] + STDP_connections[STDPoff29+kk])*Dstr;
    }
    const int outoff30 = ((x+30)*130 + y);
    const int conoff30 = 30*couple_array_size;
    const int STDPoff30 = (x*grid_size+y)*couple_array_size*couple_array_size + conoff30;
    for (int kk=(couplerange-0);kk<=(couplerange+0);kk++)
    {
        Rmat[outoff30 + kk] += (connections[conoff30+kk] + STDP_connections[STDPoff30+kk])*Rstr;
        Dmat[outoff30 + kk] += (connections[conoff30+kk] + STDP_connections[STDPoff30+kk])*Dstr;
    }
}
void check()
{
    if (conductance_array_size != 130 || couplerange != 15 || couple_array_size != 31)
    {
        printf("You need to regenerate maskgen.c");
        exit(EXIT_FAILURE);
    }
}