#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "../paramheader.h" //so we get the correct parameter values
int min(const int a,const int b) {if (a<b) {return a;} else {return b;}}
//calculate the circle
int getoffset(const int range, const int i)
{
    const double drange = (double)range;
    const double di     = (double)(i-range);
    if (drange < di) {return drange;}
    return min(range,(int) ((sqrt(drange*drange-di*di)) ));
}
int main(int argc, char** argv)
{
    //some initial setup lines
    printf("//autogenerated code - do not modify - see maskgen\n");
    printf("#include \"paramheader.h\"\n");
    printf("void evolvept_duallayer (const int x,const  int y,const Compute_float* const __restrict connections,const Compute_float strmod, Compute_float* __restrict condmat)\n");
    printf("{\n");
    printf("    int c=0;\n");
    //start the loop
    for (int i = 0; i < couple_array_size;i++)
    {
        printf("    const int outoff%i = ((x+%i)*%i + y);\n",i,i,conductance_array_size);
        char buf [1000];
        sprintf(buf,"((x+%i)*%i + y)",i,conductance_array_size);
        const int off = getoffset(couplerange,i);
        const int itercount = 2*off+1;
        printf("    for (int kk=(couplerange-%i);kk<=(couplerange+%i);kk++)\n",off,off); //this is the key part - offsets are now known at compile time
        printf("    {\n");
        printf("        condmat[outoff%i + kk] += connections[c++]*strmod;\n",i);
        printf("    }\n");
    } 
    printf("}\n");
}
